name: moviedb
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  flutter_modular: ^4.0.1+2
  equatable: ^2.0.3
  dio: ^4.0.0
  mocktail: ^0.1.4
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  mobx_codegen: ^2.0.3
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
